### ISSUE TITLE
CSS Framework Used for Project

### ISSUE THREAD

**Issue by coderchrisdean** [coderchrisdean/group_project_one#2]
https://bulma.io/

**Comment by mxu4321** [comment]
imported to css

**Comment by coderchrisdean** [comment]
Realized you imported using jsDeliver --

I changed to Bulma CDN (Linked directly to Bulma via CDN)

![Image](https://user-images.githubusercontent.com/113635027/204938186-7a9faaab-1409-4f65-8576-1ac53d40b1d9.png)
