### ISSUE TITLE
2 nba api urls

### ISSUE THREAD

**Issue by coderchrisdean** [coderchrisdean/group_project_one#7]

**Comment by mxu4321** [comment]
NBA Data:https://rapidapi.com/api-sports/api/api-nba/	All NBA Stats DATA, Games, Livescore, Standings, Statistics	apiKey	Yes	Unknown 
NBA Stats: https://any-api.com/nba_com/nba_com/docs/API_Description	Current and historical NBA Statistics	No	Yes	Unknown
